on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
        
      - name: Install sbt
        uses: coursier/setup-action@v1
        with:
          apps: sbt

      - name: Cache sbt
        uses: actions/cache@v4
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
            ~/.coursier
          key: sbt-cache-${{ runner.os }}-${{ hashFiles('**/build.sbt') }}
          restore-keys: |
            sbt-cache-${{ runner.os }}-
      
      - name: Check formatting (scalafmt)
        run: sbt scalafmtCheckAll

      - name: Run tests
        run: sbt test

